name: CI Tests
on:
  # Triggers the workflow on push or pull request events
  pull_request:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: Tests Linux
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: anaconda-client-env
          python-version: 3.8.5
          auto-activate-base: True
      - name: Install Dependencies and pyCP_APR
        run: |
          conda info
          conda list
          python setup.py install
          
      - name: Run the Unittests
        run: |
          cd tests && python -m unittest *
      
